# Generated by Django 3.2.5 on 2021-07-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('creator', models.CharField(default='samliu12', max_length=100)),
                ('lyrics', models.TextField(blank=True, default='')),
                ('pulled_lyrics', models.TextField(blank=True, default='')),
                ('chords', models.TextField(blank=True, default='')),
                ('strumming_pattern', models.CharField(blank=True, default='', max_length=30)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
    ]
