# Generated by Django 3.2.5 on 2021-07-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_of_creation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
