# Generated by Django 3.2.5 on 2021-07-27 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_comment_date_of_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.song'),
            preserve_default=False,
        ),
    ]
