# Generated by Django 3.2.6 on 2021-08-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210803_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='creator',
        ),
    ]
