# Generated by Django 3.2.6 on 2021-08-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_song_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='user',
            new_name='creator',
        ),
    ]
