# Generated by Django 3.2.5 on 2021-07-22 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_song_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songviews', '0002_remove_view_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.song'),
        ),
        migrations.AlterField(
            model_name='view',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
