# Generated by Django 3.2.6 on 2021-08-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210802_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.TextField(default='https://google.ca'),
            preserve_default=False,
        ),
    ]
